name: vy_code_generator
description: A package for dart code generator. A simpler alternative to code_generator.
version: 0.2.1
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vy_string_utils: ^0.4.0
  dart_style: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.4
