name: vy_code_generator
description: A package for dart code generator. A simpler alternative to code_generator.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  vy_string_utils: ^0.3.2
  dart_style: ^1.3.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.0
